import {useState} from "react";
import {ActivityIndicator,Alert,FlatList,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {Image} from "expo-image";
import * as ImagePicker from "expo-image-picker";
import {router} from "expo-router";
import {Ionicons} from "@expo/vector-icons";
import {completeListingWithAI,createListing} from "@/lib/api";
import {useAuth} from "@/contexts/AuthContext";
import {colors} from "@/constants/theme";
import {useLanguage} from "@/contexts/LanguageContext";
export default function Add(){
 const{tr,isRTL}=useLanguage();const align=isRTL?"right":"left";const guide=[tr("الأمام","Front"),tr("الجانب الأيمن","Right side"),tr("الجانب الأيسر","Left side"),tr("المحرك","Engine"),tr("الخلف","Rear"),tr("رقم الشاصي","VIN"),tr("الداخلية","Interior"),tr("العداد","Odometer")];
 const{user}=useAuth();const[f,setF]=useState({make:"",model:"",year:"",city:"",price:"",mileage:"",vin:"",damageType:"",legalStatus:"",whatsapp:"",description:""});const[images,setImages]=useState<string[]>([]);const[busy,setBusy]=useState(false);const[aiBusy,setAiBusy]=useState(false);const[aiNote,setAiNote]=useState("");
 const set=(k:string,v:string)=>setF(p=>({...p,[k]:v}));const gallery=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],allowsMultipleSelection:true,quality:.75,selectionLimit:8-images.length});if(!r.canceled)setImages(p=>[...p,...r.assets.map(a=>a.uri)].slice(0,8))};const camera=async()=>{await ImagePicker.requestCameraPermissionsAsync();const r=await ImagePicker.launchCameraAsync({quality:.75});if(!r.canceled)setImages(p=>[...p,r.assets[0].uri].slice(0,8))};
 const runAi=async()=>{if(images.length===0){Alert.alert("الصور مطلوبة","ارفع صورة واحدة على الأقل أولاً");return}setAiBusy(true);setAiNote("");try{const suggestion=await completeListingWithAI(images,{make:f.make,model:f.model,year:f.year,city:f.city});setF(p=>({...p,make:suggestion.make||p.make,model:suggestion.model||p.model,year:suggestion.year?String(suggestion.year):p.year,damageType:suggestion.damageType||p.damageType,description:suggestion.description||p.description,price:suggestion.suggestedPriceAED?String(suggestion.suggestedPriceAED):p.price,vin:suggestion.vin||p.vin,mileage:suggestion.mileage?String(suggestion.mileage):p.mileage}));setAiNote("تم تعبئة البيانات — راجعها قبل النشر")}catch(e:any){setAiNote(e.message||"تعذر تحليل الصور")}finally{setAiBusy(false)}};
 const submit=async()=>{if(!user)return router.push("/login");if(!f.make||!f.model||!f.city||!f.price||!f.whatsapp)return Alert.alert("الحقول المطلوبة","أدخل الماركة والموديل والمدينة والسعر ورقم التواصل");setBusy(true);try{const d=await createListing(f,images);const id=d?.data?.id||d?.id;Alert.alert("تم","تم نشر الإعلان");router.replace({pathname:"/listing/[id]",params:{id:String(id)}})}catch(e:any){Alert.alert("تعذر النشر",e.message)}finally{setBusy(false)}};
 return <ScrollView contentContainerStyle={s.page}><Text style={[s.title,{textAlign:align}]}>{tr("أضف إعلان سيارة","Add a car listing")}</Text><View style={s.sources}><Pressable style={s.source} onPress={gallery}><Ionicons name="images" size={24}/><Text>{tr("الاستديو","Gallery")}</Text></Pressable><Pressable style={s.source} onPress={camera}><Ionicons name="camera" size={24}/><Text>{tr("الكاميرا","Camera")}</Text></Pressable></View><View style={s.guide}>{guide.map((g,i)=><Text key={g} style={s.guideItem}>{i+1}. {g}</Text>)}</View><FlatList data={images} horizontal keyExtractor={(v,i)=>v+i} renderItem={({item,index})=><Pressable onPress={()=>setImages(p=>p.filter((_,i)=>i!==index))}><Image source={item} style={s.thumb}/><Text style={s.remove}>×</Text></Pressable>} style={{marginBottom:15}}/>
  <Pressable style={s.aiBtn} onPress={runAi} disabled={aiBusy}>{aiBusy?<ActivityIndicator color="#fff"/>:<Ionicons name="sparkles" size={18} color="#fff"/>}<Text style={s.aiBtnText}>{aiBusy?tr("جاري التحليل...","Analyzing..."):tr("أكمل بالذكاء الاصطناعي","Complete with AI")}</Text></Pressable>{!!aiNote&&<Text style={s.aiNote}>{aiNote}</Text>}
  {[["make",tr("الماركة","Make")],["model",tr("الموديل","Model")],["year",tr("السنة","Year")],["city",tr("المدينة","City")],["price",tr("السعر","Price")],["mileage",tr("الكيلومترات","Mileage")],["vin","VIN"],["damageType",tr("نوع الضرر","Damage type")],["legalStatus",tr("الحالة القانونية","Legal status")],["whatsapp",tr("رقم التواصل","Contact number")]].map(([k,l])=><TextInput key={k} style={s.input} placeholder={l} value={(f as any)[k]} onChangeText={v=>set(k,v)} textAlign={align} keyboardType={["year","price","mileage","whatsapp"].includes(k)?"numeric":"default"}/>)}
  <TextInput style={[s.input,{height:110}]} placeholder={tr("وصف السيارة","Car description")} value={f.description} onChangeText={v=>set("description",v)} multiline textAlignVertical="top" textAlign={align}/><Pressable style={s.submit} onPress={submit} disabled={busy}><Text style={s.submitText}>{busy?tr("جاري النشر...","Publishing..."):tr("نشر الإعلان","Publish listing")}</Text></Pressable>
 </ScrollView>
}
const s=StyleSheet.create({page:{padding:16,paddingBottom:40},title:{fontSize:25,fontWeight:"900",textAlign:"right",marginBottom:16},sources:{flexDirection:"row-reverse",gap:10},source:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:colors.line,padding:15,borderRadius:13,alignItems:"center",gap:5},guide:{flexDirection:"row-reverse",flexWrap:"wrap",backgroundColor:"#FFF8E5",padding:12,borderRadius:13,marginVertical:13,gap:7},guideItem:{width:"47%",textAlign:"right",fontSize:12},thumb:{width:95,height:72,borderRadius:10,marginRight:8},remove:{position:"absolute",top:3,right:12,color:"#fff",backgroundColor:"#000B",width:22,height:22,borderRadius:11,textAlign:"center"},aiBtn:{flexDirection:"row-reverse",backgroundColor:colors.black,padding:14,borderRadius:13,alignItems:"center",justifyContent:"center",gap:8,marginBottom:6},aiBtnText:{color:"#fff",fontWeight:"900"},aiNote:{textAlign:"right",fontSize:12,color:colors.muted,marginBottom:12},input:{backgroundColor:"#fff",borderWidth:1,borderColor:colors.line,borderRadius:13,padding:13,marginBottom:10},submit:{backgroundColor:colors.gold,padding:16,borderRadius:14},submitText:{textAlign:"center",fontWeight:"900"}})
